services:
  - type: web
    name: torque-ai-backend
    runtime: python
    buildCommand: apt-get update -y && apt-get install -y libgl1-mesa-glx libglib2.0-0 libgles2-mesa && pip install -r requirements.txt
    startCommand: gunicorn --chdir backend --timeout 120 --workers 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
